import { Bot } from './types';

export const mockBots: Bot[] = [
  {
    id: 1,
    name: 'Помощник продаж',
    description: 'ИИ-агент для автоматизации продаж в Instagram и WhatsApp',
    category: 'Продажи',
    price: 45000,
    rentPrice: 3000,
    rating: 4.8,
    users: 1240,
    icon: 'ShoppingBag',
    features: ['Квалификация лидов', 'Автоответы 24/7', 'Интеграция с CRM']
  },
  {
    id: 2,
    name: 'Консультант магазина',
    description: 'Бот-продавец для интернет-магазинов с каталогом',
    category: 'Продажи',
    price: 36000,
    rentPrice: 2500,
    rating: 4.9,
    users: 1580,
    icon: 'Store',
    features: ['Каталог товаров', 'Приём заказов', 'Расчёт доставки']
  },
  {
    id: 3,
    name: 'Лид-квалификатор',
    description: 'Фильтрация и оценка качества входящих заявок',
    category: 'Продажи',
    price: 54000,
    rentPrice: 3500,
    rating: 4.7,
    users: 890,
    icon: 'Filter',
    features: ['Скоринг лидов', 'Анкетирование', 'Передача в отдел продаж']
  },
  {
    id: 4,
    name: 'Менеджер допродаж',
    description: 'Upsell и cross-sell для существующих клиентов',
    category: 'Продажи',
    price: 48000,
    rentPrice: 3200,
    rating: 4.6,
    users: 720,
    icon: 'TrendingUp',
    features: ['Персональные предложения', 'История покупок', 'Скидки']
  },
  {
    id: 5,
    name: 'Холодные звонки',
    description: 'Бот для первичного контакта с холодной базой',
    category: 'Продажи',
    price: 42000,
    rentPrice: 2800,
    rating: 4.5,
    users: 650,
    icon: 'Phone',
    features: ['Скрипты продаж', 'Обработка возражений', 'Запись звонков']
  },
  {
    id: 6,
    name: 'Карьерный консультант',
    description: 'Продажа образовательных курсов и программ',
    category: 'Продажи',
    price: 51000,
    rentPrice: 3400,
    rating: 4.8,
    users: 540,
    icon: 'GraduationCap',
    features: ['Подбор курсов', 'Рассрочка', 'Консультации']
  },
  {
    id: 7,
    name: 'Риэлтор-помощник',
    description: 'Бот для агентств недвижимости и застройщиков',
    category: 'Продажи',
    price: 198000,
    rentPrice: 4500,
    rating: 4.7,
    users: 430,
    icon: 'Home',
    features: ['База объектов', 'Подбор по критериям', 'Запись на просмотр']
  },
  {
    id: 8,
    name: 'Туристический агент',
    description: 'Продажа туров и бронирование путешествий',
    category: 'Продажи',
    price: 171000,
    rentPrice: 3800,
    rating: 4.9,
    users: 820,
    icon: 'Plane',
    features: ['Подбор туров', 'Виза', 'Страховка']
  },
  {
    id: 9,
    name: 'Автосалон консультант',
    description: 'Продажа автомобилей с тест-драйвами',
    category: 'Продажи',
    price: 75000,
    rentPrice: 5000,
    rating: 4.6,
    users: 380,
    icon: 'Car',
    features: ['Каталог авто', 'Trade-in', 'Кредит и лизинг']
  },
  {
    id: 10,
    name: 'B2B менеджер',
    description: 'Продажи для корпоративных клиентов',
    category: 'Продажи',
    price: 84000,
    rentPrice: 5600,
    rating: 4.8,
    users: 290,
    icon: 'Building2',
    features: ['Договоры', 'Оптовые цены', 'Документооборот']
  },
  {
    id: 11,
    name: 'Клиентская поддержка',
    description: 'Бот для обработки обращений клиентов в Telegram',
    category: 'Поддержка',
    price: 36000,
    rentPrice: 2500,
    rating: 4.9,
    users: 2180,
    icon: 'Headphones',
    features: ['База знаний', 'Умные ответы', 'Эскалация в поддержку']
  },
  {
    id: 12,
    name: 'Техподдержка IT',
    description: 'Помощь пользователям с техническими проблемами',
    category: 'Поддержка',
    price: 45000,
    rentPrice: 3000,
    rating: 4.7,
    users: 1340,
    icon: 'Wrench',
    features: ['Диагностика', 'Инструкции', 'Создание тикетов']
  },
  {
    id: 13,
    name: 'FAQ-помощник',
    description: 'Автоматические ответы на частые вопросы',
    category: 'Поддержка',
    price: 24000,
    rentPrice: 1600,
    rating: 4.8,
    users: 2850,
    icon: 'MessageCircleQuestion',
    features: ['База ответов', 'Поиск', 'Обратная связь']
  },
  {
    id: 14,
    name: 'Возврат товаров',
    description: 'Обработка возвратов и рекламаций',
    category: 'Поддержка',
    price: 30000,
    rentPrice: 2000,
    rating: 4.6,
    users: 980,
    icon: 'PackageX',
    features: ['Оформление возврата', 'Трекинг', 'Компенсации']
  },
  {
    id: 15,
    name: 'Чат модератор',
    description: 'Модерация сообщений в чатах и сообществах',
    category: 'Поддержка',
    price: 27000,
    rentPrice: 1800,
    rating: 4.5,
    users: 1560,
    icon: 'Shield',
    features: ['Фильтр спама', 'Бан пользователей', 'Правила чата']
  },
  {
    id: 16,
    name: 'Жалобы и претензии',
    description: 'Работа с негативными отзывами',
    category: 'Поддержка',
    price: 39000,
    rentPrice: 2600,
    rating: 4.7,
    users: 670,
    icon: 'AlertCircle',
    features: ['Приём жалоб', 'Компенсации', 'Эскалация']
  },
  {
    id: 17,
    name: 'Онбординг клиентов',
    description: 'Обучение новых пользователей продукту',
    category: 'Поддержка',
    price: 33000,
    rentPrice: 2200,
    rating: 4.8,
    users: 1120,
    icon: 'Rocket',
    features: ['Туры по продукту', 'Видео-уроки', 'Чек-листы']
  },
  {
    id: 18,
    name: 'Статус заказа',
    description: 'Отслеживание доставки и статусов',
    category: 'Поддержка',
    price: 21000,
    rentPrice: 1400,
    rating: 4.9,
    users: 3200,
    icon: 'Package',
    features: ['Трекинг', 'Уведомления', 'История заказов']
  },
  {
    id: 19,
    name: 'Служба безопасности',
    description: 'Помощь при блокировке аккаунтов',
    category: 'Поддержка',
    price: 42000,
    rentPrice: 2800,
    rating: 4.6,
    users: 540,
    icon: 'Lock',
    features: ['Восстановление доступа', 'Верификация', '2FA']
  },
  {
    id: 20,
    name: 'Сбор отзывов',
    description: 'Автоматический сбор feedback от клиентов',
    category: 'Поддержка',
    price: 18000,
    rentPrice: 1200,
    rating: 4.7,
    users: 1890,
    icon: 'Star',
    features: ['Опросы NPS', 'Отзывы', 'Аналитика']
  },
  {
    id: 101,
    name: 'Опросник',
    description: 'Telegram бот для создания и проведения опросов с расписанием',
    category: 'Маркетинг',
    price: 24000,
    rentPrice: 1800,
    rating: 4.8,
    users: 1250,
    icon: 'ClipboardList',
    features: ['Создание опросов', 'Расписание отправки', 'Аналитика результатов', 'Множественный выбор']
  },
  {
    id: 102,
    name: 'Конструктор офферов',
    description: 'ИИ-ассистент для создания сильных офферов по методике P.R.S.T.S.',
    category: 'Маркетинг',
    price: 0,
    rentPrice: 0,
    rating: 5.0,
    users: 0,
    icon: 'Lightbulb',
    features: ['Методика P.R.S.T.S.', 'Работа со страхами', 'Разбор текущих офферов', 'Сценарии "а что если"'],
    demoUrl: '/offer-constructor'
  },
  {
    id: 21,
    name: 'HR-ассистент',
    description: 'ИИ-сотрудник для подбора персонала и онбординга',
    category: 'HR',
    price: 60000,
    rentPrice: 4500,
    rating: 4.7,
    users: 680,
    icon: 'Users',
    features: ['Скрининг резюме', 'Интервью', 'Адаптация сотрудников']
  },
  {
    id: 22,
    name: 'Рекрутер',
    description: 'Автоматический поиск и отбор кандидатов',
    category: 'HR',
    price: 66000,
    rentPrice: 4800,
    rating: 4.8,
    users: 520,
    icon: 'UserSearch',
    features: ['Парсинг резюме', 'Интервью', 'Тестирование']
  },
  {
    id: 23,
    name: 'Адаптация новичков',
    description: 'Онбординг новых сотрудников в компании',
    category: 'HR',
    price: 45000,
    rentPrice: 3000,
    rating: 4.9,
    users: 780,
    icon: 'UserPlus',
    features: ['Welcome-пакет', 'Обучение', 'Менторство']
  },
  {
    id: 24,
    name: 'Табель учёта',
    description: 'Контроль рабочего времени сотрудников',
    category: 'HR',
    price: 36000,
    rentPrice: 2400,
    rating: 4.6,
    users: 1340,
    icon: 'Clock',
    features: ['Отметки времени', 'Отпуска', 'Больничные']
  },
  {
    id: 25,
    name: 'Оценка персонала',
    description: 'Проведение аттестаций и оценки 360',
    category: 'HR',
    price: 54000,
    rentPrice: 3600,
    rating: 4.5,
    users: 430,
    icon: 'ClipboardCheck',
    features: ['Опросы', 'KPI', 'Отчёты']
  },
  {
    id: 26,
    name: 'Корпоративное обучение',
    description: 'Организация тренингов и курсов',
    category: 'HR',
    price: 48000,
    rentPrice: 3200,
    rating: 4.7,
    users: 590,
    icon: 'BookOpen',
    features: ['Курсы', 'Тесты', 'Сертификаты']
  },
  {
    id: 27,
    name: 'Helpdesk для HR',
    description: 'Ответы на вопросы сотрудников',
    category: 'HR',
    price: 42000,
    rentPrice: 2800,
    rating: 4.8,
    users: 920,
    icon: 'HelpCircle',
    features: ['База знаний', 'Политики', 'Документы']
  },
  {
    id: 28,
    name: 'Выход сотрудников',
    description: 'Offboarding и Exit-интервью',
    category: 'HR',
    price: 39000,
    rentPrice: 2600,
    rating: 4.6,
    users: 380,
    icon: 'UserMinus',
    features: ['Чек-листы', 'Интервью', 'Документы']
  },
  {
    id: 29,
    name: 'Корпоративная культура',
    description: 'Поддержка ценностей и вовлечённости',
    category: 'HR',
    price: 51000,
    rentPrice: 3400,
    rating: 4.7,
    users: 540,
    icon: 'Heart',
    features: ['Опросы', 'Мероприятия', 'Признание']
  },
  {
    id: 30,
    name: 'Wellness-бот',
    description: 'Забота о здоровье сотрудников',
    category: 'HR',
    price: 45000,
    rentPrice: 3000,
    rating: 4.9,
    users: 670,
    icon: 'Activity',
    features: ['Напоминания', 'Советы', 'Трекинг']
  },
  {
    id: 31,
    name: 'Маркетолог-аналитик',
    description: 'Анализ рекламных кампаний и ROI',
    category: 'Маркетинг',
    price: 75000,
    rentPrice: 6000,
    rating: 4.8,
    users: 540,
    icon: 'BarChart3',
    features: ['Дашборды', 'ROI', 'Рекомендации']
  },
  {
    id: 32,
    name: 'SMM-менеджер',
    description: 'Управление социальными сетями',
    category: 'Маркетинг',
    price: 60000,
    rentPrice: 5000,
    rating: 4.7,
    users: 820,
    icon: 'Share2',
    features: ['Публикации', 'Аналитика', 'Комментарии']
  },
  {
    id: 33,
    name: 'Email-маркетолог',
    description: 'Автоматизация email-рассылок',
    category: 'Маркетинг',
    price: 54000,
    rentPrice: 4500,
    rating: 4.9,
    users: 1240,
    icon: 'Mail',
    features: ['Сегментация', 'A/B тесты', 'Персонализация']
  },
  {
    id: 34,
    name: 'Контент-менеджер',
    description: 'Генерация и публикация контента',
    category: 'Маркетинг',
    price: 66000,
    rentPrice: 5500,
    rating: 4.6,
    users: 690,
    icon: 'FileText',
    features: ['Идеи', 'Написание', 'SEO']
  },
  {
    id: 35,
    name: 'Таргетолог',
    description: 'Настройка рекламы в соцсетях',
    category: 'Маркетинг',
    price: 69000,
    rentPrice: 5800,
    rating: 4.8,
    users: 760,
    icon: 'Target',
    features: ['Аудитории', 'Креативы', 'Оптимизация']
  },
  {
    id: 36,
    name: 'SEO-специалист',
    description: 'Продвижение в поисковых системах',
    category: 'Маркетинг',
    price: 72000,
    rentPrice: 6000,
    rating: 4.7,
    users: 580,
    icon: 'Search',
    features: ['Аудит', 'Ключевые слова', 'Линкбилдинг']
  },
  {
    id: 37,
    name: 'CRM-маркетолог',
    description: 'Автоматизация воронок и триггеров',
    category: 'Маркетинг',
    price: 63000,
    rentPrice: 5200,
    rating: 4.9,
    users: 920,
    icon: 'GitBranch',
    features: ['Воронки', 'Сегменты', 'Скоринг']
  },
  {
    id: 38,
    name: 'Инфлюенс-маркетолог',
    description: 'Работа с блогерами и лидерами мнений',
    category: 'Маркетинг',
    price: 57000,
    rentPrice: 4800,
    rating: 4.6,
    users: 430,
    icon: 'Users2',
    features: ['Поиск блогеров', 'Сделки', 'Отчёты']
  },
  {
    id: 39,
    name: 'Чат-бот маркетолог',
    description: 'Конверсионные диалоги с клиентами',
    category: 'Маркетинг',
    price: 60000,
    rentPrice: 5000,
    rating: 4.8,
    users: 1150,
    icon: 'MessageSquare',
    features: ['Квизы', 'Лид-формы', 'Интеграции']
  },
  {
    id: 40,
    name: 'Event-маркетолог',
    description: 'Организация вебинаров и мероприятий',
    category: 'Маркетинг',
    price: 66000,
    rentPrice: 5500,
    rating: 4.7,
    users: 540,
    icon: 'Calendar',
    features: ['Регистрация', 'Напоминания', 'Follow-up']
  },
  {
    id: 41,
    name: 'Бухгалтер-ассистент',
    description: 'Автоматизация учёта и отчётности',
    category: 'Финансы',
    price: 90000,
    rentPrice: 8000,
    rating: 4.8,
    users: 1240,
    icon: 'Calculator',
    features: ['Проводки', 'Отчёты', 'Налоги']
  },
  {
    id: 42,
    name: 'Финансовый аналитик',
    description: 'Анализ прибыли и убытков',
    category: 'Финансы',
    price: 96000,
    rentPrice: 8500,
    rating: 4.9,
    users: 680,
    icon: 'TrendingUp',
    features: ['P&L', 'Cash Flow', 'Прогнозы']
  },
  {
    id: 43,
    name: 'Контроль расходов',
    description: 'Мониторинг и оптимизация затрат',
    category: 'Финансы',
    price: 84000,
    rentPrice: 7000,
    rating: 4.7,
    users: 920,
    icon: 'PiggyBank',
    features: ['Бюджеты', 'Лимиты', 'Алерты']
  },
  {
    id: 44,
    name: 'Инвойс-менеджер',
    description: 'Выставление и отслеживание счетов',
    category: 'Финансы',
    price: 78000,
    rentPrice: 6500,
    rating: 4.6,
    users: 1580,
    icon: 'FileSpreadsheet',
    features: ['Счета', 'Акты', 'Напоминания']
  },
  {
    id: 45,
    name: 'Валютный контроль',
    description: 'Работа с мультивалютными операциями',
    category: 'Финансы',
    price: 87000,
    rentPrice: 7500,
    rating: 4.8,
    users: 430,
    icon: 'DollarSign',
    features: ['Курсы', 'Конвертация', 'Хеджирование']
  },
  {
    id: 46,
    name: 'Казначей',
    description: 'Управление денежными потоками',
    category: 'Финансы',
    price: 93000,
    rentPrice: 8000,
    rating: 4.7,
    users: 340,
    icon: 'Wallet',
    features: ['Платежи', 'Ликвидность', 'Прогнозы']
  },
  {
    id: 47,
    name: 'Налоговый помощник',
    description: 'Расчёт и подача налоговых деклараций',
    category: 'Финансы',
    price: 99000,
    rentPrice: 9000,
    rating: 4.9,
    users: 780,
    icon: 'Receipt',
    features: ['НДС', 'Прибыль', 'Отчёты']
  },
  {
    id: 48,
    name: 'Закрытие месяца',
    description: 'Автоматизация month-end close',
    category: 'Финансы',
    price: 102000,
    rentPrice: 9500,
    rating: 4.6,
    users: 520,
    icon: 'CheckCircle2',
    features: ['Реконсиляция', 'Проводки', 'Отчёты']
  },
  {
    id: 49,
    name: 'Кредитный контроль',
    description: 'Управление дебиторской задолженностью',
    category: 'Финансы',
    price: 81000,
    rentPrice: 7000,
    rating: 4.8,
    users: 640,
    icon: 'CreditCard',
    features: ['Лимиты', 'Напоминания', 'Коллекции']
  },
  {
    id: 50,
    name: 'Аудитор',
    description: 'Внутренний контроль и проверки',
    category: 'Финансы',
    price: 105000,
    rentPrice: 10000,
    rating: 4.7,
    users: 290,
    icon: 'ShieldCheck',
    features: ['Проверки', 'Риски', 'Рекомендации']
  },
  {
    id: 51,
    name: 'Юрист-консультант',
    description: 'Правовые консультации и документы',
    category: 'Юриспруденция',
    price: 120000,
    rentPrice: 12000,
    rating: 4.8,
    users: 540,
    icon: 'Scale',
    features: ['Консультации', 'Договоры', 'Споры']
  },
  {
    id: 52,
    name: 'Договорная работа',
    description: 'Подготовка и проверка договоров',
    category: 'Юриспруденция',
    price: 114000,
    rentPrice: 11000,
    rating: 4.7,
    users: 820,
    icon: 'FileSignature',
    features: ['Шаблоны', 'Проверка', 'Согласование']
  },
  {
    id: 53,
    name: 'Претензионная работа',
    description: 'Досудебное урегулирование споров',
    category: 'Юриспруденция',
    price: 126000,
    rentPrice: 13000,
    rating: 4.9,
    users: 380,
    icon: 'AlertTriangle',
    features: ['Претензии', 'Переговоры', 'Медиация']
  },
  {
    id: 54,
    name: 'Корпоративный юрист',
    description: 'Сопровождение корпоративных процедур',
    category: 'Юриспруденция',
    price: 132000,
    rentPrice: 14000,
    rating: 4.6,
    users: 290,
    icon: 'Building',
    features: ['Протоколы', 'Регистрация', 'Реорганизация']
  },
  {
    id: 55,
    name: 'IP-юрист',
    description: 'Защита интеллектуальной собственности',
    category: 'Юриспруденция',
    price: 138000,
    rentPrice: 15000,
    rating: 4.8,
    users: 240,
    icon: 'Copyright',
    features: ['Патенты', 'Товарные знаки', 'Лицензии']
  },
  {
    id: 56,
    name: 'HR-юрист',
    description: 'Трудовое право и кадровый учёт',
    category: 'Юриспруденция',
    price: 111000,
    rentPrice: 10500,
    rating: 4.7,
    users: 680,
    icon: 'Briefcase',
    features: ['Договоры', 'Увольнения', 'Споры']
  },
  {
    id: 57,
    name: 'Комплаенс-офицер',
    description: 'Соответствие законодательству',
    category: 'Юриспруденция',
    price: 144000,
    rentPrice: 16000,
    rating: 4.9,
    users: 320,
    icon: 'CheckSquare',
    features: ['Аудит', 'Политики', 'Обучение']
  },
  {
    id: 58,
    name: 'GDPR-специалист',
    description: 'Защита персональных данных',
    category: 'Юриспруденция',
    price: 129000,
    rentPrice: 13500,
    rating: 4.6,
    users: 430,
    icon: 'Lock',
    features: ['Согласия', 'Политики', 'DPA']
  },
  {
    id: 59,
    name: 'Налоговый юрист',
    description: 'Налоговое планирование и споры',
    category: 'Юриспруденция',
    price: 135000,
    rentPrice: 14500,
    rating: 4.8,
    users: 290,
    icon: 'Receipt',
    features: ['Оптимизация', 'Проверки', 'Споры']
  },
  {
    id: 60,
    name: 'Судебный представитель',
    description: 'Представительство в судах',
    category: 'Юриспруденция',
    price: 150000,
    rentPrice: 17000,
    rating: 4.7,
    users: 180,
    icon: 'Gavel',
    features: ['Иски', 'Заседания', 'Апелляции']
  },
  {
    id: 61,
    name: 'Нейрофотосессия',
    description: 'AI-генерация профессиональных фотографий с помощью нейросетей',
    category: 'Креатив',
    price: 75000,
    rentPrice: 6500,
    rating: 4.9,
    users: 1540,
    icon: 'Camera',
    features: ['Генерация фото', 'FLUX & Stable Diffusion', 'Профессиональное качество', 'OpenRouter API']
  }
];